apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
# 服务如果想被外部调用，必须配置type
  type: NodePort
  ports:
  - port: 8080
    name: service-port
#   服务如果想被外部调用，必须配置nodePort
    nodePort: 31002
  - port: 8005
    name: shutdown-port
  selector:
    tier: frontend